### ISSUE TITLE
Using `measure contacts` double selection

### ISSUE THREAD

**Issue by RasmusFonseca** [getcontacts/getcontacts#41]
The current implementation of double selection uses `measure contacts` with a single selection and then filters to only contain the desired interactions across the two selections using methods like this one:

https://github.com/getcontacts/getcontacts/blob/91001b5a4d9884d98cb5f8b59817aa151a4f08c6/contact_calc/aromatics.py#L31-L61

I just noticed that `measure contacts` has an optional second selection that would probably speed this up significantly and simplify our code:

> `contacts cutoff selection1 [selection2]`: Find all atoms in `selection1` that are within `cutoff` of any atom in `selection2` and not bonded to it. If `selection2` is omitted, it is taken to be the same as `selection1`. `selection2` and `selection1` can either be from the same of from different molecules. Returns two lists of atom indices, the first containing the first index of each pair (taken from `selection1`) and the second containing the second index (taken from `selection2`). Note that the index is the global index of the atom with respect to its parent molecule, as opposed to the index within the given atom selection that contains it.
> https://www-s.ks.uiuc.edu/Research/vmd/vmd-1.9.1/ug/node136.html

This would ideally be updated a couple of places.

**Comment by RasmusFonseca** [comment]
This seems to work: https://github.com/getcontacts/getcontacts/blob/master/contact_calc/hydrophobics.py

**Comment by akma327** [comment]
This is a good point, the second selection option was used previously for measure contacts $cation_atom $aromatic_atom. Introducing this call improved vanderwaals by a good amount, not so for aromatics. 

It seems like the hydrophobics module you added is giving empty output due to the "element C S" command. Will close this issue for now, but feel free to update the hydrophobics.py if it's intended to be a standalone module.
